/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DkSideDrawer {
        "drawerTitle": string;
        "open": () => Promise<void>;
        "opened": boolean;
    }
    interface DkSpinner {
    }
    interface DkStockFinder {
    }
    interface DkStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLDkSideDrawerElement extends Components.DkSideDrawer, HTMLStencilElement {
    }
    var HTMLDkSideDrawerElement: {
        prototype: HTMLDkSideDrawerElement;
        new (): HTMLDkSideDrawerElement;
    };
    interface HTMLDkSpinnerElement extends Components.DkSpinner, HTMLStencilElement {
    }
    var HTMLDkSpinnerElement: {
        prototype: HTMLDkSpinnerElement;
        new (): HTMLDkSpinnerElement;
    };
    interface HTMLDkStockFinderElement extends Components.DkStockFinder, HTMLStencilElement {
    }
    var HTMLDkStockFinderElement: {
        prototype: HTMLDkStockFinderElement;
        new (): HTMLDkStockFinderElement;
    };
    interface HTMLDkStockPriceElement extends Components.DkStockPrice, HTMLStencilElement {
    }
    var HTMLDkStockPriceElement: {
        prototype: HTMLDkStockPriceElement;
        new (): HTMLDkStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "dk-side-drawer": HTMLDkSideDrawerElement;
        "dk-spinner": HTMLDkSpinnerElement;
        "dk-stock-finder": HTMLDkStockFinderElement;
        "dk-stock-price": HTMLDkStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface DkSideDrawer {
        "drawerTitle"?: string;
        "opened"?: boolean;
    }
    interface DkSpinner {
    }
    interface DkStockFinder {
        "onDkSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface DkStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "dk-side-drawer": DkSideDrawer;
        "dk-spinner": DkSpinner;
        "dk-stock-finder": DkStockFinder;
        "dk-stock-price": DkStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dk-side-drawer": LocalJSX.DkSideDrawer & JSXBase.HTMLAttributes<HTMLDkSideDrawerElement>;
            "dk-spinner": LocalJSX.DkSpinner & JSXBase.HTMLAttributes<HTMLDkSpinnerElement>;
            "dk-stock-finder": LocalJSX.DkStockFinder & JSXBase.HTMLAttributes<HTMLDkStockFinderElement>;
            "dk-stock-price": LocalJSX.DkStockPrice & JSXBase.HTMLAttributes<HTMLDkStockPriceElement>;
        }
    }
}
